apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
      - image: carlosedp/blackbox_exporter:v0.12.0
        name: blackbox-exporter
        ports:
        - containerPort: 9115
          name: metrics
