#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: kube-state-metrics
#    k8s-app: kube-state-metrics
#  name: kube-state-metrics
#spec:
#  #clusterIP: None
#  ports:
#  - name: http-main
#    protocol: TCP
#    port: 8443
#    targetPort: 8443
#  - name: http-self
#    protocol: TCP
#    port: 9443
#    targetPort: 9443
#  selector:
#    app: kube-state-metrics

apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  #namespace: kube-system
  labels:
    k8s-app: kube-state-metrics
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    protocol: TCP
  - name: telemetry
    port: 8081
    targetPort: telemetry
    protocol: TCP
  selector:
    k8s-app: kube-state-metrics
