{
 "title": "Traefik  Ingress Metrics",
 "description": "Visualize Traefik Metrics",
 "tags": [ "Traefik" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Average Response Time (ms)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_backend_request_duration_seconds_sum) / sum(traefik_backend_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{endpoint=\"admin\"}"
    }
   ]
  },
  {
   "title": "404 Error Count last 5 Minutes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=\"404\",method=\"GET\"}[5m])) * 1000"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_backend_requests_total)",
     "legendFormat": "{{http}}"
    }
   ]
  },
  {
   "title": "Requests by Request Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, traefik_backend_requests_total{service!~\"http\"})",
     "legendFormat": "{{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Requests/sec in last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total[5m]))",
     "legendFormat": "{{requests}}"
    }
   ]
  },
  {
   "title": "Successful Status Code Count (5min)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_backend_requests_total{code=\"200\"}[5m])",
     "legendFormat": "{{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Bad Status Code Count (5m)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_backend_requests_total{code!=\"200\"}[5m])",
     "legendFormat": "{{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Requests/sec by ingress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"20.+|30.+\"}[5m])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  }
 ]
}