apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  rules:
  # Changed this to match your DNS name
  - host: alertmanager.thepracticalsysadmin.com
    http:
      paths:
      - path: /
        backend:
          serviceName: alertmanager-main
          servicePort: web

